language: perl
sudo: false
perl:
 - "5.12"
 - "5.14"
 - "5.16"
 - "5.18"
 - "5.20"
 - "5.22"
 - "5.24"
 - "5.26"
matrix:
  include:
    - perl: 5.18
      env: COVERAGE=1   # enables coverage+coveralls reporting
  allow_failures:
    - perl: blead       # ignore failures for blead perl
before_install:
  - git clone git://github.com/haarg/perl-travis-helper
  - source perl-travis-helper/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR

install:
  - export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=c HARNESS_TIMER=1
  - cpanm --quiet --notest Devel::Cover::Report::Coveralls Pod::Coverage::TrustPod Test::CPAN::Meta
  - cpanm --quiet --notest --installdeps .
  - cpanm --quiet --notest --with-develop .

script:
  - PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine prove -lrsv t
  - cover

after_success:
  - cover -report coveralls